### ISSUE TITLE
Package app as flatpak

### ISSUE THREAD

**Issue by adrm** [anetczuk/LinakDeskApp#11]
Having this app as Flatpak will be great since it will make it easily installable in every Linux distro that supports Flatpak, which is almost everyone. Uploading it to https://flathub.org/ will make it visible and allow everyone to easily install it.

**Comment by anetczuk** [comment]
I made installation of application as easy as I could by providing `configure_all.sh`. Installation process needs to be supervised because of dependencies and various nuances. Feel free to contribute.
