### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by dmitrym0** [anetczuk/LinakDeskApp#12]
Similar to #6, I wonder if this would work on MacOS? 

It seems that Bluepy is Linux only. Is that correct?

**Comment by anetczuk** [comment]
I do not have access to MacOS, so unable to check it by myself. Yes, documentation says that bluepy/bluez is for Linux strictly.

Have just found alternatives: [bleak](https://pypi.org/project/bleak/) and pybluez. They seems to be Linux/Windows/MacOS friendly.

**Comment by ex-nerd** [comment]
https://github.com/rhyst/idasen-controller uses bleak and works great with my Linak controller.  It's missing features compared to LinakDeskApp, but would be cool if things could be combined (separate the cli and gui).

**Comment by anetczuk** [comment]
I do not have access to MacOS, so can't test implementation. Please feel free to contribute.
