### ISSUE TITLE
Please license linak_bt_desk

### ISSUE THREAD

**Issue by ex-nerd** [anetczuk/LinakDeskApp#13]
This repo contains an MIT license, but the https://github.com/anetczuk/linak_bt_desk/ library doesn't, which makes it hard to know if another app (e.g. if I were to fork https://github.com/rhyst/idasen-controller) would be able to use it.

(that repo doesn't include an issue tracker, so am filing this here)

See companion ticket in upstream repo here: https://github.com/zewelor/linak_bt_desk/issues/3

**Comment by anetczuk** [comment]
License synced with upstream project.
