### ISSUE TITLE
Missing executable bit on install_reqs.sh

### ISSUE THREAD

**Issue by D0han** [anetczuk/LinakDeskApp#15]
Minor stuff, just noticed that configure_all.sh fails on executing install_reqs.sh
```
$ ./configure_all.sh 
Installing dependencies
./configure_all.sh: line 13: /[...]/LinakDeskApp/src/install_reqs.sh: Permission denied
```

Other than that, seems that configure_all.sh nor configure_autostart.sh is called during installation.

Thanks for the project!

**Comment by anetczuk** [comment]
Thanks for issue. Problem solved.
